### ISSUE TITLE
Tests using testflo not working

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#231]
## Description
I have been using version 1.0.0 for a long time and it has been working well. I thought I'd pull some changes from upstream, and am now on 2.5.1.

After rebuilding this latest version, I try to run `testflo . -v`, but only 3 tests passed, 3 failed and 39 skipped.

Any idea why the tests don't seem to pick up any of the optimizers?

Here is the output after running testflo:

```
./test/test_hs015.py:TestHS15.test_conmin ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'CONMIN')
./test/test_rosenbrock.py:TestRosenbrock.test_ipopt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'IPOPT')
./test/test_rosenbrock.py:TestRosenbrock.test_nlpqlp ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'NLPQLP')
./test/test_rosenbrock.py:TestRosenbrock.test_paropt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'ParOpt')
./test/test_rosenbrock.py:TestRosenbrock.test_psqp ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'PSQP')
./test/test_rosenbrock.py:TestRosenbrock.test_slsqp ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'SLSQP')
./test/test_rosenbrock.py:TestRosenbrock.test_snopt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'SNOPT')
./test/test_hs015.py:TestHS15.test_ipopt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'IPOPT')
./test/test_tp109.py:TestTP109.test_slsqp ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'slsqp')
./test/test_tp109.py:TestTP109.test_snopt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'SNOPT')
./test/test_hs071.py:TestHS71.test_conmin ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'conmin')
./test/test_hs071.py:TestHS71.test_ipopt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'ipopt')
./test/test_hs071.py:TestHS71.test_nlpqlp ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'nlpqlp')
./test/test_hs015.py:TestHS15.test_snopt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'SNOPT')
./test/test_hs071.py:TestHS71.test_paropt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'paropt')
./test/test_hs071.py:TestHS71.test_psqp ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'psqp')
./test/test_hs071.py:TestHS71.test_slsqp ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'slsqp')
./test/test_hs071.py:TestHS71.test_slsqp_scaling_offset_optProb ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'slsqp')
./test/test_hs071.py:TestHS71.test_slsqp_setDV ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'SLSQP')
./test/test_hs071.py:TestHS71.test_snopt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'SNOPT')
./test/test_hs015.py:TestHS15.test_nlpqlp ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'NLPQLP')
./test/test_hs071.py:TestHS71.test_snopt_setDVFromHist ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'SNOPT')
./test/test_optProb.py:TestOptProb.test_setDV_VarGroup ... FAIL (00:00:0.00, 61 MB)
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/CADA/lib/python3.9/site-packages/testflo/test.py", line 425, in _try_call
    func()
  File "./test/test_optProb.py", line 125, in test_setDV_VarGroup
    self.setup_optProb(
  File "./test/test_optProb.py", line 96, in setup_optProb
    opt = OPT("slsqp", options={"IFILE": "optProb_SLSQP.out"})
  File "/home/michael/pyoptsparse/pyoptsparse/pyOpt_optimizer.py", line 957, in OPT
    return opt(*args, **kwargs)
  File "/home/michael/pyoptsparse/pyoptsparse/pySLSQP/pySLSQP.py", line 35, in __init__
    raise Error("There was an error importing the compiled slsqp module")
pyoptsparse.pyOpt_error.Error

./test/test_optProb.py:TestOptProb.test_mappings ... FAIL (00:00:0.01, 61 MB)
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/CADA/lib/python3.9/site-packages/testflo/test.py", line 425, in _try_call
    func()
  File "./test/test_optProb.py", line 152, in test_mappings
    self.setup_optProb(
  File "./test/test_optProb.py", line 96, in setup_optProb
    opt = OPT("slsqp", options={"IFILE": "optProb_SLSQP.out"})
  File "/home/michael/pyoptsparse/pyoptsparse/pyOpt_optimizer.py", line 957, in OPT
    return opt(*args, **kwargs)
  File "/home/michael/pyoptsparse/pyoptsparse/pySLSQP/pySLSQP.py", line 35, in __init__
    raise Error("There was an error importing the compiled slsqp module")
pyoptsparse.pyOpt_error.Error

./test/test_nsga2_multi_objective.py:TestNSGA2.test_opt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'NSGA2')
./test/test_optProb.py:TestOptProb.test_setDV_getDV ... FAIL (00:00:0.00, 61 MB)
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/CADA/lib/python3.9/site-packages/testflo/test.py", line 425, in _try_call
    func()
  File "./test/test_optProb.py", line 103, in test_setDV_getDV
    self.setup_optProb(
  File "./test/test_optProb.py", line 96, in setup_optProb
    opt = OPT("slsqp", options={"IFILE": "optProb_SLSQP.out"})
  File "/home/michael/pyoptsparse/pyoptsparse/pyOpt_optimizer.py", line 957, in OPT
    return opt(*args, **kwargs)
  File "/home/michael/pyoptsparse/pyoptsparse/pySLSQP/pySLSQP.py", line 35, in __init__
    raise Error("There was an error importing the compiled slsqp module")
pyoptsparse.pyOpt_error.Error

./test/test_hs015.py:TestHS15.test_slsqp ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'SLSQP')
./test/test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug1 ... SKIP (00:00:0.00, 61 MB)
Optimizer not available: SNOPT
./test/test_snopt_bugfix.py:TestSNOPTBug.test_opt ... SKIP (00:00:0.00, 61 MB)
Optimizer not available: SNOPT
./test/test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug_print_2con ... SKIP (00:00:0.00, 61 MB)
Optimizer not available: SNOPT
./test/test_hs015.py:TestHS15.test_psqp ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'PSQP')
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_do_not_use_mpi ... OK (00:00:0.00, 61 MB)
./test/test_rosenbrock.py:TestRosenbrock.test_conmin ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'CONMIN')
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_no_mpi_requirement_given ... OK (00:00:0.00, 61 MB)
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVar.test_require_mpi ... OK (00:00:0.00, 61 MB)
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_no_mpi_requirement_given_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_do_not_use_mpi_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./test/test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_require_mpi_check_paropt ... SKIP (00:00:0.00, 61 MB)
('Optimizer not available:', 'paropt')
./test/test_snopt_user_termination.py:TestUserTerminationStatus.test_obj ... SKIP (00:00:0.00, 61 MB)
Optimizer not available: SNOPT
./test/test_snopt_user_termination.py:TestUserTerminationStatus.test_sens ... SKIP (00:00:0.00, 61 MB)
Optimizer not available: SNOPT
./test/test_hs015.py:TestHS15.test_paropt ... SKIP (00:00:0.00, 60 MB)
('Optimizer not available:', 'ParOpt')
./test/test_large_snopt.py:TestLarge.test_dense_default ... SKIP (00:00:0.03, 64 MB)
Optimizer not available: SNOPT
./test/test_large_snopt.py:TestLarge.test_dense_user ... SKIP (00:00:0.03, 64 MB)
Optimizer not available: SNOPT
./test/test_large_snopt.py:TestLarge.test_sparse ... SKIP (00:00:1.25, 137 MB)
Optimizer not available: SNOPT
./test/test_tp109.py:TestTP109.test_autorefine ... SKIP (00:00:15.45, 61 MB)
('Optimizer not available:', 'SNOPT')


The following tests were skipped:
test_hs015.py:TestHS15.test_conmin
test_hs015.py:TestHS15.test_ipopt
test_hs015.py:TestHS15.test_nlpqlp
test_hs015.py:TestHS15.test_paropt
test_hs015.py:TestHS15.test_psqp
test_hs015.py:TestHS15.test_slsqp
test_hs015.py:TestHS15.test_snopt
test_hs071.py:TestHS71.test_conmin
test_hs071.py:TestHS71.test_ipopt
test_hs071.py:TestHS71.test_nlpqlp
test_hs071.py:TestHS71.test_paropt
test_hs071.py:TestHS71.test_psqp
test_hs071.py:TestHS71.test_slsqp
test_hs071.py:TestHS71.test_slsqp_scaling_offset_optProb
test_hs071.py:TestHS71.test_slsqp_setDV
test_hs071.py:TestHS71.test_snopt
test_hs071.py:TestHS71.test_snopt_setDVFromHist
test_large_snopt.py:TestLarge.test_dense_default
test_large_snopt.py:TestLarge.test_dense_user
test_large_snopt.py:TestLarge.test_sparse
test_nsga2_multi_objective.py:TestNSGA2.test_opt
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_do_not_use_mpi_check_paropt
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_no_mpi_requirement_given_check_paropt
test_require_mpi_env_var.py:TestRequireMPIEnvVarOnParOpt.test_require_mpi_check_paropt
test_rosenbrock.py:TestRosenbrock.test_conmin
test_rosenbrock.py:TestRosenbrock.test_ipopt
test_rosenbrock.py:TestRosenbrock.test_nlpqlp
test_rosenbrock.py:TestRosenbrock.test_paropt
test_rosenbrock.py:TestRosenbrock.test_psqp
test_rosenbrock.py:TestRosenbrock.test_slsqp
test_rosenbrock.py:TestRosenbrock.test_snopt
test_snopt_bugfix.py:TestSNOPTBug.test_opt
test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug1
test_snopt_bugfix.py:TestSNOPTBug.test_opt_bug_print_2con
test_snopt_user_termination.py:TestUserTerminationStatus.test_obj
test_snopt_user_termination.py:TestUserTerminationStatus.test_sens
test_tp109.py:TestTP109.test_autorefine
test_tp109.py:TestTP109.test_slsqp
test_tp109.py:TestTP109.test_snopt


The following tests failed:
test_optProb.py:TestOptProb.test_mappings
test_optProb.py:TestOptProb.test_setDV_VarGroup
test_optProb.py:TestOptProb.test_setDV_getDV


Passed:  3
Failed:  3
Skipped: 39


Ran 45 tests using 8 processes
Wall clock time:   00:00:16.16
```

### Code versions
- pyoptsparse: 2.5.1
- Python: 3.6.13

**Comment by nwu63** [comment]
As shown by the error message, this indicates that the shared libraries were not compiled correctly during installation. There can be a number of causes
- If you did a developer install (with `-e`), check if there are duplicate `.so` files in the subdirectories, e.g. `pyoptsparse/pySLSQP`. If so, manually delete all `.so` files and install again.
- Are you actually running Python 3.6? Your log shows that `testflo` at least is installed under Python 3.9. And what is the version of numpy you are using?
- If none of these are the cause, and there is just a single `.so` file in each subdirectory, try importing one of them in the python shell, e.g.
  ```
  cd pyoptsparse/pySLSQP
  python
  >>> import slsqp
  ```
  and confirm that you get some sort of `missing symbol` error. Then we can try to figure it out from there.

**Comment by michK** [comment]
Hi Neil,

Thanks for the response.

I made some progress. I think some of the problem was related to downgrading from Python 3.9 to 3.6 and forgetting to install `testflo` under 3.6, as well as not setting my `PYTHONPATH` to `pyoptsparse` properly.

I have the SNOPT wrapper working now, which is all I really need.

Thanks
Michael
