### ISSUE TITLE
pyOpt vs pyoptsparse: different behavior

### ISSUE THREAD

**Issue by michK** [mdolab/pyoptsparse#24]
Good day.

The following program runs fine for me:

```
import pyOpt

def objfunc(x):

    f = -x[0] * x[1] * x[2]
    g = [0.0] * 2
    g[0] = x[0] + 2. * x[1] + 2. * x[2] - 72.0
    g[1] = -x[0] - 2. * x[1] - 2. * x[2]

    fail = 0
    return f, g, fail

opt_prob = pyOpt.Optimization('TP37 Constrained Problem', objfunc)

opt_prob.addObj('f')

opt_prob.addVar('x1', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x2', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x3', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addConGroup('g', 2, 'i')

print(opt_prob)

slsqp = pyOpt.SLSQP()

[fstr, xstr, inform] = slsqp(opt_prob)

print(opt_prob.solution(0))
```

Giving the solution:

```
--------------------------------------------------------------------------------
    Total Time:                    0.0031
    Total Function Evaluations:         0
    Sensitivities:        FD

    Objectives:
        Name        Value        Optimum
	     f           -3456             0

	Variables (c - continuous, i - integer, d - discrete):
        Name    Type       Value       Lower Bound  Upper Bound
	     x1       c	     24.000000       0.00e+00     4.20e+01
	     x2       c	     12.000000       0.00e+00     4.20e+01
	     x3       c	     12.000000       0.00e+00     4.20e+01

	Constraints (i - inequality, e - equality):
        Name    Type                    Bounds
	    g_0   	  i       -1.00e+21 <= 0.000000 <= 0.00e+00
	    g_1   	  i       -1.00e+21 <= -72.000000 <= 0.00e+00

--------------------------------------------------------------------------------
```

However, changing `pyOpt` to `pyoptsparse` as:

```
import pyoptsparse

def objfunc(x):

    f = -x[0] * x[1] * x[2]
    g = [0.0] * 2
    g[0] = x[0] + 2. * x[1] + 2. * x[2] - 72.0
    g[1] = -x[0] - 2. * x[1] - 2. * x[2]

    fail = 0
    return f, g, fail


opt_prob = pyoptsparse.Optimization('TP37 Constrained Problem', objfunc)

opt_prob.addObj('f')

opt_prob.addVar('x1', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x2', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x3', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addConGroup('g', 2, 'i')

print(opt_prob)

slsqp = pyoptsparse.SLSQP()

[fstr, xstr, inform] = slsqp(opt_prob)

print(opt_prob.solution(0))
```

gives the error:

```
File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_optimization.py", line 522, in addConGroup
    name, nCon, linear, wrt, jac, lower, upper, scale)
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_constraint.py", line 51, in __init__
    lower = lower*numpy.ones(self.ncon)
TypeError: ufunc 'multiply' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')
```

Am I missing something that you can perhaps not just interchange `pyOpt` and `pyoptsparse` command like this?

Thanks for any feedback

**Comment by johnjasa** [comment]
It appears that the API between `pyOpt` and `pyOptSparse` differs slightly in this case. It comes from the `'i'` argument in the call to `addConGroup`.

In `pyOpt`, the API is [here](http://www.pyopt.org/reference/classes.optimization.html?highlight=addcongroup#pyOpt_optimization.Optimization.addConGroup) and you can set whether the constraint is an inequality or equality constraint.

However, in `pyOptSparse`, the [API for `addConGroup`](https://github.com/mdolab/pyoptsparse/blob/master/pyoptsparse/pyOpt_optimization.py#L437) shows that you do not need to specify the type of constraint. Instead, you can set the `lower` or `upper` bound for an inequality constraint, or both for an equality constraint.

In general, the API between the two codes should be similar, but may be different. Most of the methods in `pyOptSparse` are documented well, but please open another issue if anything's unclear or could be improved.

Thanks for your great detail and question! Let me know if this doesn't solve your issue.

**Comment by michK** [comment]
Hi John,

Thank you for your prompt response.

Unfortunately, I haven't had the chance to have a look at this again, but I will close this issue so long since it definitely just looks like a difference in API's.

Thanks again
Michael

**Comment by michK** [comment]
Good day John, just a quick followup.

I believe the following problem is now set up according to the pyoptsparse API:

```
import pyoptsparse

def objfunc(x):

    f = -x['x1'] * x['x2'] * x['x3']
    g = {}
    g['g1'] = x['x1'] + 2. * x['x2'] + 2. * x['x3'] - 72.0
    g['g2'] = -x['x1'] - 2. * x['x2'] - 2. * x['x3']

    fail = 0
    return f, g, fail

opt_prob = pyoptsparse.Optimization('TP37 Constrained Problem', objfunc)

opt_prob.addObj('f')

opt_prob.addVar('x1', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x2', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addVar('x3', 'c', lower=0.0, upper=42.0, value=10.0)
opt_prob.addCon('g1', upper=0)
opt_prob.addCon('g2', upper=0)

print(opt_prob)

slsqp = pyoptsparse.SLSQP()

[fstr, xstr, inform] = slsqp(opt_prob, sens='FD')
# [fstr, xstr, inform] = slsqp(opt_prob)

print(opt_prob.solution(0))

```

But this results in the error:

```
capi_return is NULL
Call-back cb_slfunc_in_slsqp__user__routines failed.
Traceback (most recent call last):
  File "test_slsqp_pyoptsparse.py", line 29, in <module>
    [fstr, xstr, inform] = slsqp(opt_prob, sens='FD')
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 238, in __call__
    ngrad, slfunc, slgrad)
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pySLSQP/pySLSQP.py", line 188, in slfunc
    fobj, fcon, fail = self._masterFunc(x, ['fobj', 'fcon'])
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_optimizer.py", line 296, in _masterFunc
    result = self._masterFunc2(*args)
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_optimizer.py", line 350, in _masterFunc2
    fcon = self.optProb.processConstraints(funcs)
  File "/Users/user/miniconda3/lib/python3.6/site-packages/pyoptsparse/pyOpt_optimization.py", line 1184, in processConstraints
    if iCon in fcon_in:
TypeError: argument of type 'numpy.float64' is not iterable
```
I understand that the function `processConstraints` is trying to iterate over a float, which is not possible, but I can't quite figure out why it is trying to do that.

Thanks for any insights
Michael

**Comment by johnjasa** [comment]
Hey Michael, I can't fully resolve this right now but I believe you'll need to modify your objFunc. Check out one of the pyOptSparse examples here for some of the syntax. You should be able to mirror it for your problem. Note that this differs from pyOpt's suggested way of setting up the problem.

https://github.com/mdolab/pyoptsparse/blob/master/examples/hs071.py

I can take a look later again if you check out these examples and still have the same issue.

**Comment by michK** [comment]
Hi John,

Thank you very much for the info.

Michael
