### ISSUE TITLE
SNOPT tests failing on stable images

### ISSUE THREAD

**Issue by eirikurj** [mdolab/pyoptsparse#369]
## Description
With changes from PR https://github.com/mdolab/pyoptsparse/pull/364, SNOPT tests are failing on stable images during nightly tests with `fStar` reported as 0 (see for example [here](https://github.com/mdolab/docker/actions/runs/7096395939/job/19314852484#step:13:13471)).

### Steps to reproduce issue
Any stable image with changes from https://github.com/mdolab/pyoptsparse/pull/364 will generate similar errors as below

```
Traceback (most recent call last):
  File "/home/mdolabuser/repos/pyoptsparse/tests/test_tp109.py", line 205, in test_autorefine
    self.assert_solution_allclose(sol2, 1e-2)
  File "/home/mdolabuser/repos/pyoptsparse/tests/testing_utils.py", line 123, in assert_solution_allclose
    assert_allclose(sol.fStar, self.fStar[self.sol_index], atol=tol, rtol=tol)
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/home/mdolabuser/.pyenv/versions/3.9.16/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.01, atol=0.01

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 5362.06927538
Max relative difference: 1.
 x: array(0.)
 y: array(5362.069275)
```

### Current behavior
SNOPT tests on stable images are failing

### Expected behavior
All tests should pass

### Code versions
Any stable image with changes from https://github.com/mdolab/pyoptsparse/pull/364

**Comment by eirikurj** [comment]
Had a very brief look, and it seems like SNOPT is just returning 0 for `obj`. Using v7.7.7 on stable works, passing all tests, but v7.7.1 and v7.7.5, fail the tests. Not sure if we want to drop support for SNOPT < v7.7.7 with this version and onwards.
