### ISSUE TITLE
ParOpt error at opt call

### ISSUE THREAD

**Issue by kmodexc** [mdolab/pyoptsparse#384]
## Description
When you select the ParOpt optimizer, you cant start it with the current version.

Here the error:
```
Traceback (most recent call last):
  File "/workspaces/luxsim/pyopttest.py", line 104, in <module>
    sol = opt(optProb, sens="FD")
  File "/usr/local/lib/python3.10/dist-packages/pyoptsparse/pyParOpt/ParOpt.py", line 225, in __call__
    problem = Problem(self, n, m, xs, blx, bux)
  File "/usr/local/lib/python3.10/dist-packages/pyoptsparse/pyParOpt/ParOpt.py", line 176, in __init__
    super().__init__(MPI.COMM_SELF, n, m)
  File "paropt/ParOpt.pyx", line 788, in paropt.ParOpt.Problem.__init__
TypeError: __init__() takes exactly 1 positional argument (3 given)
```

### Steps to reproduce issue

It could be probably even simpler, but this reproduces the error for me:
```
from pyoptsparse import ParOpt, Optimization

def objfunc(xdict):
    x = xdict["xvars"]
    funcs = {}
    funcs["obj"] = -x[0] * x[1] * x[2]
    fail = False
    return funcs, fail

optProb = Optimization("TP037 Constraint Problem", objfunc)
optProb.addVarGroup("xvars", 3, "c", lower=[0, 0, 0], upper=[42, 42, 42], value=10)
optProb.addObj("obj")
opt = ParOpt()
sol = opt(optProb, sens="FD")
```

Also here the dockerfile to reproduce the dependencys:
```

FROM ubuntu
RUN apt update
RUN apt install -y git cmake build-essential libomp-dev libblas-dev liblapack-dev libopenmpi-dev python3 python3-pip

RUN python3 -m pip install torch

WORKDIR /opt
RUN git clone https://github.com/KarypisLab/GKlib.git
WORKDIR /opt/GKlib
RUN make config && make && make install

WORKDIR /opt
RUN git clone https://github.com/KarypisLab/METIS.git
WORKDIR /opt/METIS
RUN make config && make && make install

RUN apt install -y libblas-dev liblapack-dev libopenmpi-dev openmpi-bin

ENV PAROPT_DIR "/root/git/paropt"
ENV METIS_DIR "/root/local"
ENV PATH "$PATH:$PAROPT_DIR:$METIS_DIR"
ENV PYTHONPATH "$PYTHONPATH:$PAROPT_DIR"

WORKDIR /root/git
RUN git clone https://github.com/smdogroup/paropt.git
WORKDIR /root/git/paropt
RUN cp Makefile.in.info Makefile.in
RUN sed -i "s/libmetis.a/libmetis.a \/root\/local\/lib\/libGKlib.a/g" Makefile.in
RUN make

RUN python3 -m pip install ipykernel Cython mpi4py numpy matplotlib
#RUN python3 setup.py install
RUN make interface
#RUN "python3 -m pip install -e .\\[all\\]"
RUN python3 -c "from paropt import ParOpt"

WORKDIR /opt
RUN git clone https://github.com/mdolab/pyoptsparse.git
WORKDIR pyoptsparse
RUN python3 -m pip install meson
RUN apt install -y ninja-build
RUN python3 -m pip install .

```

1. docker build .
2. docker run -it <tag> /bin/bash
3. create the example in the container (here called example.py)
4. python3 example.py

### Current behavior
```
Traceback (most recent call last):
  File "/workspaces/luxsim/pyopttest.py", line 104, in <module>
    sol = opt(optProb, sens="FD")
  File "/usr/local/lib/python3.10/dist-packages/pyoptsparse/pyParOpt/ParOpt.py", line 225, in __call__
    problem = Problem(self, n, m, xs, blx, bux)
  File "/usr/local/lib/python3.10/dist-packages/pyoptsparse/pyParOpt/ParOpt.py", line 176, in __init__
    super().__init__(MPI.COMM_SELF, n, m)
  File "paropt/ParOpt.pyx", line 788, in paropt.ParOpt.Problem.__init__
TypeError: __init__() takes exactly 1 positional argument (3 given)
```

### Expected behavior
- No error - 

### Code versions

- Operating System: Ubuntu
- Python: 3.10.12
- OpenMPI: 4.1.2
- CGNS: ?
- PETSc: ?
- Compiler: gcc 11.4.0
- This repository: 604aeda

**Comment by kmodexc** [comment]
Solved it by writing the 2nd and 3rd argument like [here](https://smdogroup.github.io/paropt/sellar.html):
```
class Sellar(ParOpt.Problem):
    def __init__(self):
        # Initialize the base class
        nvars = 4
        ncon = 1
        super(Sellar, self).__init__(MPI.COMM_SELF, nvars=nvars, ncon=ncon)
```
